tap 'homebrew/cask'
tap 'microsoft/git'

brew 'git'
brew 'node'
brew 'nvm'
brew 'volta'
brew 'zsh'
brew 'zsh-completions'
brew 'kubectl'

cask 'visual-studio-code'
cask 'git-credential-manager'
cask 'iterm2'